Singleton
BloopApp/Bloop pull request #18
Opened 2016-12-06 15:21 UTC by segerphilip

Adds an Application class that can be used as a singleton for location or playlogin objects. Also, bugfix, hides the login button on success.

2016-12-06 22:18 UTC, wolfd requested changes
Looks great.

Did you know that for some reason, we can edit each other's comments? That's not going to go badly.

Yes Danny. Yes it will.

2016-12-06 22:18 UTC, wolfd commented on app/src/main/java/website/bloop/app/BloopApplication.java
> +        if(mInstance == null)
small nit: keep the starting bracket on the same line as the if, and have a space after the `if` and before the `(`.

2016-12-06 22:20 UTC, sammyers commented on app/src/main/java/website/bloop/app/BloopApplication.java
> +    public static BloopApplication getInstance(){
Yo where's that space

2016-12-06 22:20 UTC, sammyers commented on app/src/main/java/website/bloop/app/BloopApplication.java
> +        if(mInstance == null)
savage

2016-12-06 22:46 UTC, segerphilip commented on app/src/main/java/website/bloop/app/BloopApplication.java
> +        if(mInstance == null)
oh man how did I miss this sorry

2016-12-09 19:02 UTC, wolfd approved these changes
A+

2016-12-09 19:02 UTC, merged